version: '3.7'
services:
  app:
    build: ./
    command: "bin/snippets start"
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
  db:
    image: "postgres:12-alpine"
    ports:
      - "${DB_PORT}:5432"
    env_file: .env
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"

